---
  - id: validate
    name: Home Assistant Config Validator
    description: Validate the Home Assistant configuration
    entry: poetry run validate
    language: python
    args: []
    additional_dependencies: []
    always_run: true
