---
  - id: validate-entities
    name: Home Assistant Config Validator
    description: Validate the Home Assistant entities directory
    entry: poetry run validate-entities
    language: python
    args: []
    additional_dependencies:
      - sqlalchemy
    always_run: true
    require_serial: true
    pass_filenames: false
