---
  - id: validate-entities
    name: Home Assistant Config Validator
    description: Validate the Home Assistant entities directory
    entry: poetry run validate-entities
    language: python
    args: []
    additional_dependencies:
      - gitpython
      - homeassistant==2023.5.4
      - poetry
      - sqlalchemy
      - wg-utilities
    always_run: true
    require_serial: true
    pass_filenames: false
