---
  - id: validate
    name: Home Assistant Config Validator
    description: Validate the Home Assistant configuration
    entry: python home_assistant_config_validator/main.py
    language: python
    args: []
    additional_dependencies: []
    always_run: true
