---
name: Create New Release

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  create-new-release:
    name: Create New Release
    # yamllint disable-line rule:line-length
    uses: worgarside/github-config-files/.github/workflows/create_new_release.yml@feature/create-new-release-overwrite-function
    secrets:
      gh-token: ${{ secrets.WORGARSIDE_DEV_TOKEN }}
